exp_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/exps/jeff_tennis_swing_trimmed"
format: "release"
videos:
  root_dir: "/pasteur/u/jeffheo/projects/nemo-cvpr2023-jeff/data/videos/jeff/trimmed"
  names:
    [
      "tennis_swing.0",
      "tennis_swing.1",
      "tennis_swing.2",
      "tennis_swing.3",
      "tennis_swing.4",
      "tennis_swing.5",
    ]
